# Generated by Django 4.2 on 2023-05-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discout',
            new_name='discount',
        ),
    ]
